version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    resource_class: medium+
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile && npm run test
  coverage:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/balancer
    steps:
      - run:
          name: Coverage
          command: npm run coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls

workflows:
  sc-tests:
    jobs:
      - test
      - coverage
